# Generated by Django 4.2.3 on 2023-09-05 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postmodel',
            options={'ordering': ('-publication_date',)},
        ),
    ]
